fix: added relative paths for github pages

diff --git a/.github/workflows/version_sementic.yml b/.github/workflows/version_sementic.yml
--- a/.github/workflows/version_sementic.yml
+++ b/.github/workflows/version_sementic.yml
@@ -35,26 +35,20 @@ jobs:
         latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep '^refs/tags/')
         if [[ -n "$latest_tag" ]]; then
           latest_tag=$(echo "$latest_tag" | head -n 1 | cut -d '/' -f 3)
-
-          # Filter tags based on the desired format
-          latest_tag=$(echo "$latest_tag" | grep "^v[0-9]+\.[0-9]+\.[0-9]+$")
-          if [[ -n "$latest_tag" ]]; then
-            echo "Latest tag: $latest_tag"
-            # Proceed with the rest of the steps using the filtered tag
-          else
-            echo "No tags found in the desired format"
-            set -e  # Fail the job if no tags in the desired format are found
-          fi
+          echo "Latest tag: $latest_tag"
         else
           echo "No tags found"
-          set -e
+          exit 1
+        fi
 
-          echo "Latest tag: $latest_tag"
+        latest_tag="${latest_tag#v}"
+        echo "Latest tag: $latest_tag"
 
+        IFS='.' read -ra version <<< "$latest_tag"
 
-        else
-        echo "No tags found"
-
+        if [[ ! -n "${version[0]}" ]] || [[ ! -n "${version[1]}" ]] || [[ ! -n "${version[2]}" ]]; then
+          echo "Invalid semantic version format: $latest_tag"
+          exit 1
         fi
 
         latest_tag="${latest_tag#v}"
@@ -86,4 +80,3 @@ jobs:
         #push the tags
 
         git push origin "$NEW_VERSION"
-
