fix: added relative paths for github pages

diff --git a/.github/workflows/version_sementic.yml b/.github/workflows/version_sementic.yml
--- a/.github/workflows/version_sementic.yml
+++ b/.github/workflows/version_sementic.yml
@@ -34,16 +34,17 @@ jobs:
         
         latest_tag=$(git for-each-ref --sort=-creatordate --format='%(refname)' | grep '^refs/tags/')
         if [[ -n "$latest_tag" ]]; then
-
-          latest_tag=$(echo "$latest_tag" | head -n 1 | cut -d '/' -f 3)
+        latest_tag=$(echo "$latest_tag" | head -n 1 | cut -d '/' -f 3)
+        # Filter tags based on the desired format using awk
+        latest_tag=$(echo "$latest_tag" | awk '/^v[0-9]+\.[0-9]+\.[0-9]+$/')
+        if [[ -n "$latest_tag" ]]; then
           echo "Latest tag: $latest_tag"
-
-          latest_tag=$(echo "$latest_tag" | awk '/^v[0-9]+\.[0-9]+\.[0-9]+$/')
-          echo "tag after validation: $latest_tag"
-
+          # Proceed with the rest of the steps using the filtered tag
         else
-        echo "No tags found"
+          echo "No tags found in the desired format"
+          exit 1  # Fail the job if no tags in the desired format are found
         fi
+     
 
         latest_tag="${latest_tag#v}"
         echo "Latest tag: $latest_tag"
