checking

diff --git a/.github/workflows/version_sementic.yml b/.github/workflows/version_sementic.yml
--- a/.github/workflows/version_sementic.yml
+++ b/.github/workflows/version_sementic.yml
@@ -65,10 +65,12 @@ jobs:
         echo "Latest version is: $NEW_VERSION"
 
         if git rev-parse -q --verify "refs/tags/$latest_tag" >/dev/null; then
-            git tag -a -m "Incrementing existing version to $NEW_VERSION" "$latest_tag"
+          git tag -a -m "Incrementing existing version to $MAJOR.$MINOR.$PATCH" "$latest_tag"
+          git push origin --tags --force  # Force-push the updated tag
+          echo "Existing tag '$latest_tag' incremented to $MAJOR.$MINOR.$PATCH"
         else
-            # Create the new tag
-            git tag -a -m "Incrementing patch version to $NEW_VERSION" "$NEW_VERSION"
+        echo "Tag '$latest_tag' not found in the desired format"
+        exit 1
         fi
 
         # create the new tag 
